### ISSUE TITLE
Upgrade version 1.2.5 problem

### ISSUE THREAD

**Issue by acivan** [ocombe/ng2-translate#13]
EXCEPTION: No provider for Http! (App -> TranslateService -> Http)
browser_adapter.js:76EXCEPTION: No provider for Http! (App -> TranslateService -> Http)BrowserDomAdapter.logError @ browser_adapter.js:76BrowserDomAdapter.logGroup @ browser_adapter.js:86ExceptionHandler.call @ exception_handler.js:56(anonymous function) @ application_ref.js:183NgZone._notifyOnError @ ng_zone.js:430errorHandling.onError @ ng_zone.js:328run @ core.js:99(anonymous function) @ ng_zone.js:343zoneBoundFn @ core.js:69lib$es6$promise$$internal$$tryCatch @ es6-promise.js:326lib$es6$promise$$internal$$invokeCallback @ es6-promise.js:338lib$es6$promise$$internal$$publish @ es6-promise.js:309(anonymous function) @ microtask.js:37microtask @ ng_zone.js:383run @ core.js:96(anonymous function) @ ng_zone.js:343zoneBoundFn @ core.js:69lib$es6$promise$asap$$flush @ es6-promise.js:120
browser_adapter.js:76STACKTRACE:BrowserDomAdapter.logError @ browser_adapter.js:76ExceptionHandler.call @ exception_handler.js:58(anonymous function) @ application_ref.js:183NgZone._notifyOnError @ ng_zone.js:430errorHandling.onError @ ng_zone.js:328run @ core.js:99(anonymous function) @ ng_zone.js:343zoneBoundFn @ core.js:69lib$es6$promise$$internal$$tryCatch @ es6-promise.js:326lib$es6$promise$$internal$$invokeCallback @ es6-promise.js:338lib$es6$promise$$internal$$publish @ es6-promise.js:309(anonymous function) @ microtask.js:37microtask @ ng_zone.js:383run @ core.js:96(anonymous function) @ ng_zone.js:343zoneBoundFn @ core.js:69lib$es6$promise$asap$$flush @ es6-promise.js:120
browser_adapter.js:76Error: DI Exception
    at NoProviderError.BaseException [as constructor] (exceptions.js:15)
    at NoProviderError.AbstractProviderError [as constructor] (exceptions.js:38)
    at new NoProviderError (exceptions.js:74)
    at Injector._throwOrNull (injector.js:852)
    at Injector._getByKeyDefault (injector.js:903)
    at Injector._getByKey (injector.js:843)
    at Injector._getByDependency (injector.js:829)
    at Injector._instantiate (injector.js:721)
    at Injector._instantiateProvider (injector.js:712)
    at Injector._new (injector.js:701)BrowserDomAdapter.logError @ browser_adapter.js:76ExceptionHandler.call @ exception_handler.js:59(anonymous function) @ application_ref.js:183NgZone._notifyOnError @ ng_zone.js:430errorHandling.onError @ ng_zone.js:328run @ core.js:99(anonymous function) @ ng_zone.js:343zoneBoundFn @ core.js:69lib$es6$promise$$internal$$tryCatch @ es6-promise.js:326lib$es6$promise$$internal$$invokeCallback @ es6-promise.js:338lib$es6$promise$$internal$$publish @ es6-promise.js:309(anonymous function) @ microtask.js:37microtask @ ng_zone.js:383run @ core.js:96(anonymous function) @ ng_zone.js:343zoneBoundFn @ core.js:69lib$es6$promise$asap$$flush @ es6-promise.js:120
bootstrap.ts:18NoProviderError {message: "No provider for Http! (App -> TranslateService -> Http)", stack: "Error: DI Exception↵    at NoProviderError.BaseExc…ttp://127.0.0.1:8899/__build__/common.js:9511:22)", keys: Array[3], injectors: Array[3]}

----------------------------------
note：V 1.2.4 is OK。

**Comment by ocombe** [comment]
It's probably because you need to load the HTTP_PROVIDERS in your bootstrap:

```
bootstrap(AppComponent, [
    HTTP_PROVIDERS,
    TranslateService
]);
```

**Comment by acivan** [comment]
Hi, everything is ok when I switch back to 1.2.4. But it does not work with 1.2.5. HTTP_PROVIDERS is loaded in bootstrap()

**Comment by ocombe** [comment]
And you use angular 2 beta 1 ?

**Comment by acivan** [comment]
Yes,I use angular 2 beta 1 .

**Comment by acivan** [comment]
I know the problem ，Because I will useStaticFilesLoader written in the front.

**Comment by ocombe** [comment]
This bug has been fixed in the latest version (1.3.1), you shouldn't have a problem like this anymore.
