### ISSUE TITLE
Ionic2-Meteor integration

### ISSUE THREAD

**Issue by mjwheatley** [ocombe/ng2-translate#57]
I have an Angular2-Meteor project using the barbatus:ionic2-meteor package for Ionic2.

I have successfully used the ng2-translate module with a regular Ionic2 app, but I'm having trouble getting it to work in a meteor project (v1.2.1).  I do not know how use the SystemJS module loader to load npm modules for use in the project.  I keep getting Cannot find module 'ng2-translate/ng2-translate'

How do I configure my Meteor project to use the ng2-translate module?

**Comment by ocombe** [comment]
I have no idea, I've never used Meteor. Let's call on the expertise of @Urigo and see if he knows :)

**Comment by Urigo** [comment]
@mjwheatley can you post this issue on the Angular2Meteor repo?

**Comment by mjwheatley** [comment]
It looks like Meteor 1.3 will be the solution with the addition of the modules package that will allow you to use native npm modules on both client and server.  However, @Urigo has not yet published the angular2-meteor and angular2-meteor-auto-bootstrap node modules for use with Meteor 1.3 as referenced in the Quick Start section of the angular2-meteor package readme.

**Comment by mjwheatley** [comment]
@ocombe would you be willing to publish this as an atmosphere package for Meteor?
Here is a [link to the response](https://github.com/Urigo/angular2-meteor/issues/174#event-593689348) I receive from @barbatus on the issue I submitted on the Angular2Meteor repo.

**Comment by ocombe** [comment]
You just need a system_config.js file ? If that's all then you can make a PR and I'll merge it

**Comment by Urigo** [comment]
@mjwheatley now everything is updated and you can use any npm library you want with angular2-meteor.
@ocombe I think we can close this.
@mjwheatley if you still have issues, you can open new ones on the angular2-meteor repo

**Comment by ocombe** [comment]
Ok thanks!

**Comment by tomitbe** [comment]
Hi ocombe, Urigo, still struggling with integrating ng-translate in ionic2 and Angular2... is this already supported?

**Comment by ocombe** [comment]
yes, you can check the official ionic super starter that uses ng2 translate: https://github.com/driftyco/ionic-starter-super

**Comment by tomitbe** [comment]
Ok thank you, I'll give it a try... there is an issue on ocombe/ng2-translate (bottom page) that says: "Ionic 2 is still using angular 2 RC4, but ng2-translate uses RC5. You should fix the version of ng2-translate to 2.2.2 until Ionic 2 upgrades to RC5.", but I would like to use the latest version... not an issue anymore?

**Comment by ocombe** [comment]
no sorry, this is an old artefact from the readme, I already removed it on the branch for the next release :)

**Comment by tomitbe** [comment]
Hi Ocombe, I have tried to integrate but for Meteor there is something weird going on.

When I use it in app module like below, it works fine (I need to place the i18n folder in the public folder!)

app.module.ts:
...
import { TranslateModule } from 'ng2-translate';
...
// Modules
  imports: [
    IonicModule.forRoot(AppComponent),
    HttpModule,
    TranslateModule.forRoot()  
  ],  


When I try to use the TranslateLoader/translateStaticLoader, it goes totally wrong (my client error is "Uncaught SyntaxError: Unexpected token export" in ng2-translate.ts):
this is part of my code like I found in your example:

import { TranslateModule, TranslateLoader, TranslateStaticLoader } from 'ng2-translate/ng2-translate';

export function createTranslateLoader(http: Http) {
    return new TranslateStaticLoader(http, './i18n', '.json');
}

**Comment by ocombe** [comment]
What version of angular / ng2 translate are you using ?

**Comment by tomitbe** [comment]
version 5.0.0

**Comment by ocombe** [comment]
Could you try to remove the import of `HttpModule` ? I think the `IonicModule` already provides it

**Comment by tomitbe** [comment]
Hi Ocombe, I tried to remove the import but then it says that the HttpModule is not known.

**Comment by ocombe** [comment]
Hmm no idea then, I'd need a plunkr or a project somewhere to find out the problem

**Comment by mjwheatley** [comment]
@tomitbe I have successfully integrated ng2-translate in my [ionic2-meteor-boilerplate](https://github.com/mjwheatley/ionic2-meteor-boilerplate) project.  Please refer to my project's configuration and see if you can get your's working.

**Comment by tomitbe** [comment]
@ocombe this is my Meteor repo: https://github.com/tomitbe/cignos
@mjwheatley thank you for your advise! I got it also working with i18n folder in public folder, but I try to avoid the situation having the i18n folder in the public... this by using the translateStaticLoader but that is exactly not working.

**Comment by mjwheatley** [comment]
@tomitbe did you try this from the `ng2-translate` README:
AoT

If you want to configure a custom TranslateLoader while using AoT compilation or Ionic 2, you must use an exported function instead of an inline function.
```
export function createTranslateLoader(http: Http) {
    return new TranslateStaticLoader(http, './assets/i18n', '.json');
}

@NgModule({
    imports: [
        BrowserModule,
        HttpModule,
        TranslateModule.forRoot({
            provide: TranslateLoader,
            useFactory: (createTranslateLoader),
            deps: [Http]
        })
    ],
    bootstrap: [AppComponent]
})
export class AppModule { }
```

Why do you want to avoid using the public directory?

**Comment by tomitbe** [comment]
@mjwheatley yes I did and checked also with the exported function.
it goes totally wrong soon as I import the TranslateLoader and TranslateStaticLoader, with or without using the exported function...
Even when I just use  TranslateModule.forRoot(); it crashes just after using the "import" of the modules above:
import { TranslateModule, TranslateLoader, TranslateStaticLoader } from 'ng2-translate/ng2-translate';

very strange

**Comment by mjwheatley** [comment]
The import should be from 'ng2-translate` or from `ng2-translate/index`
See if that makes a difference.

**Comment by mjwheatley** [comment]
I got the TranslateLoader to work in my application with the following:

```
import { IonicApp, IonicModule, IonicErrorHandler } from 'ionic-angular';
import { BrowserModule } from "@angular/platform-browser";
import { HttpModule, Http } from '@angular/http';
import { TranslateModule, TranslateLoader, TranslateStaticLoader } from 'ng2-translate';

export function createTranslateLoader(http: Http) {
    return new TranslateStaticLoader(http, './assets/i18n', '.json');
}

@NgModule({
//...
imports: [
        BrowserModule,
        HttpModule,
        TranslateModule.forRoot({
            provide: TranslateLoader,
            useFactory: (createTranslateLoader),
            deps: [Http]
        }),
        IonicModule.forRoot(AppComponent, {
            //// http://ionicframework.com/docs/v2/api/config/Config/
            //mode: Constants.STYLE.MD,
            //pageTransition: Constants.STYLE.IOS,
            //swipeBackEnabled: false,
            //tabbarPlacement: 'top'
        }),
    ],
    // Main Component
    bootstrap: [IonicApp]
})
```

**Comment by tomitbe** [comment]
@mjwheatley yeeesss ... this works... apparently the import was wrong assigned, though I followed the documentation of cocombe... should be import { TranslateModule, TranslateLoader, TranslateStaticLoader } from 'ng2-translate'; indeed... thanks you!!!

**Comment by ocombe** [comment]
Where did you see an import from `'ng2-translate/ng2-translate';` ? We should have cleaned them all from the docs, but if it's still there somewhere, tell me where :)

**Comment by tomitbe** [comment]
Hi Ocombe, it's in the ionic-super-starter:

https://github.com/driftyco/ionic-starter-super/blob/master/src/app/app.module.ts

**Comment by ocombe** [comment]
Damn, I'll have to do a PR... They did it with an old version of ng2 translate

**Comment by tomitbe** [comment]
:-) thanks for your support, happy that I can use the ng2-translate module now, works great!
